spring:
  profiles:
    active: china
  data:
    mongodb:
      database:
  freemarker:
    check-template-location: false

  redis:
    connect-timeout: 5S
    timeout: 5S

server:
  servlet:
    context-path: /blackboard

#Server Config
#Host-name: csse
#Password: DidiHenryChet433*
#IP: 8.140.144.182
#Username: root
global:
  db-usrnm: admin
  db-pswd: DidiHenryChet

application:
  config:
    # Turn this on to allow users to communicate to one another without being mutual friends.
    allow-no-friend-communication: true
    # Turn this on to see error messages in the frontend/Postman.
    show-detailed-error-message: true
    #Redis Heart beat(in seconds)
    redis-heart-beat: 3


mybatis-plus:
  mapper-locations: classpath:/**/*Mapper.xml


