server-config:
  ip: 8.140.144.182
  cassandra-ip: 433-17.csse.rose-hulman.edu

spring:
  data:
    cassandra:
      keyspace-name: blackboard
      contact-points: ${server-config.cassandra-ip}
      port: 9042
      local-datacenter: datacenter1
      username: ${global.db-usrnm}
      password: ${global.db-pswd}

    mongodb:
      host: ${server-config.ip}
      port: 27017
      username: ${global.db-usrnm}
      password: ${global.db-pswd}
      authentication-database: admin
      database: blackboard

  redis:
    host: ${server-config.ip}
    port: 6379
    password: ${global.db-pswd}