spring:
  profiles:
    active: china

server:
  servlet:
    context-path: /blackboard

#Server Config
#Host-name: csse
#Password: DidiHenryChet433*
#IP: 8.140.144.182
#Username: root
global:
  db-usrnm: admin
  db-pswd: DidiHenryChet

application:
  config:
    allow-no-friend-communication: true

